### ISSUE TITLE
HTFanControl.Main.HTFanControl.LoadVideoTimecodes Function does not help user debug issues with invalid formatted wind file

### ISSUE THREAD

**Issue by joshuatedesco** [nicko88/HTFanControl#23]
Issue found in top gun (1986) wind track.

Add better error handling and logging here

https://github.com/nicko88/HTFanControl/blob/25954d8da52ba5fb215527427987ee9df501009a/HTFanControl/Main/HTFanControl.cs#L384-L386

does not detect invalid delimiter

ex: 
expected: 00:42:49,OFF
actual: 00:42:49;OFF

error in crashlog:
Index was outside the bounds of the array.

HTFanControl

   at HTFanControl.Main.HTFanControl.LoadVideoTimecodes(String fileName, String filePath)
   at HTFanControl.Main.HTFanControl.SyncVideo()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by nicko88** [comment]
Thanks for this report!

I'll get it fixed up soon and definitely improve the windtrack parsing and error handling.
